### PR TITLE
doc: fix broken Wikipedia link in README

### PR DESCRIPTION
**Pull request by bytemare**

### CODE REVIEW

**Comment by mmcloughlin** [comment]
Good catch, thanks!

It looks like the CI workflow didn't run on this PR. Not sure why. Perhaps it was disabled because if inactivity on the repo for a while.

Anyway, if it ran it would have told you the README.md was out-of-date with the template it's generated from:

https://github.com/mmcloughlin/addchain/blob/d2e18230e751ba765be3d234d3c483469decdcbd/internal/tools/docgen/templates/readme.tmpl#L59

Perhaps you could update this too?

I'm happy to fix it too ([and give you credit](https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors)).

**Comment by bytemare** [comment]
Done 😃 

I think the CI workflow is not running because `first-time contributors need a maintainer to approve running workflows.`

**Comment by mmcloughlin** [comment]
> Done 😃

Thanks!

> I think the CI workflow is not running because `first-time contributors need a maintainer to approve running workflows.`

Yeah, I wasn't even seeing that button before. The CI workflow was disabled after 60 days of inactivity.

**Comment by mmcloughlin** [comment]
Thanks!

**Pull request merged**
